all sorts of changes

diff --git a/dot-zshrc b/dot-zshrc
--- a/dot-zshrc
+++ b/dot-zshrc
@@ -49,7 +49,6 @@ fi
 
 paths=(
   "$HOME/go/bin"
-  "$HOME/.cargo/bin"
   "$HOME/.local/bin"
   "$HOME/perl5/bin"
 )
@@ -65,6 +64,20 @@ if command -v nvim >/dev/null 2>&1; then
   alias v=nvim
 fi
 export EDITOR PATH
+
+zd() {
+  if [ $# -eq 0 ]; then
+    builtin cd ~ && return
+  elif [ -d "$1" ]; then
+    builtin cd "$1"
+  else
+    z "$@" && printf " \U000F17A9 " && pwd || echo "Error: Directory not found"
+  fi
+}
+
+open() {
+  xdg-open "$@" >/dev/null 2>&1
+}
 
 init_tool() {
   local tool=$1
@@ -94,31 +107,18 @@ init_tool zoxide init zsh
 alias ez='nvim ~/.zshrc'
 alias rz='source ~/.zshrc'
 alias j=jobs
-#alias l='ls -GlaF'
-#alias lr='ls -FartlG'
+alias lr='ls -FartlG'
 alias l='eza -lh --group-directories-first --icons=auto'
 alias lsa='ls -a'
 alias lt='eza --tree --level=2 --long --icons --git'
 alias lta='lt -a'
 alias ff="fzf --preview 'bat --style=numbers --color=always {}'"
 alias cd="zd"
-zd() {
-  if [ $# -eq 0 ]; then
-    builtin cd ~ && return
-  elif [ -d "$1" ]; then
-    builtin cd "$1"
-  else
-    z "$@" && printf " \U000F17A9 " && pwd || echo "Error: Directory not found"
-  fi
-}
-open() {
-  xdg-open "$@" >/dev/null 2>&1
-}
 
 # Directories
-alias ..='cd ..'
-alias ...='cd ../..'
-alias ....='cd ../../..'
+alias ..= 'cd ..'
+alias ...= 'cd ../..'
+alias ....= 'cd ../../..'
 
 # Tools
 alias v='nvim'
@@ -128,4 +128,5 @@ alias g='git'
 alias gcm='git commit -m'
 alias gcam='git commit -a -m'
 alias gcad='git commit -a --amend'
+alias claude="/home/markp/.claude/local/claude"
 
